# Generated by Django 3.1.4 on 2020-12-23 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201223_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 11, 40, 7, 127125, tzinfo=utc)),
        ),
    ]
