# Generated by Django 3.1.4 on 2020-12-30 09:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20201225_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activation',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 9, 5, 42, 49642, tzinfo=utc)),
        ),
    ]
