# Generated by Django 3.1.4 on 2020-12-23 15:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201223_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 15, 5, 46, 79476, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='moduser',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=18, null=True),
        ),
    ]
