# Generated by Django 3.1.4 on 2020-12-23 15:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20201223_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 12, 25, 15, 19, 29, 917769, tzinfo=utc)),
        ),
    ]
